name: Deploy Alghawali Frontend to VPS
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add GitHub to known hosts
      run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - name: Deploy frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          cd /root/alghawali/alghawali/alghawaliAccess/alghawali-access-frontend
          git remote set-url origin git@github.com:umarrfarooooq/alghawali-access-frontend.git
          git fetch origin master
          git reset --hard origin/master
          npm install
          npm run build
          rm -rf /var/www/training/*
          mkdir -p /var/www/training/client
          cp -r dist/* /var/www/training/client
